import { Mochiy_Pop_One, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const mochiyPopOne = Mochiy_Pop_One({
  variable: "--font-mochiy-pop-one",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "BrainStack",
  description: "Generated by Eftajul Islam Shadi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${mochiyPopOne.variable} ${poppins.variable}`}>
        {/* Navbar */}
        <header className="h-[88px]">
        <Navbar />
        </header>

        {/* Main Content */}
        <main className="min-h-[calc(100vh-88px)]">{children}</main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
